CREATE TABLE labs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE staff_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    lab_id BIGINT NOT NULL,
    FOREIGN KEY (lab_id) REFERENCES labs(id)
);

CREATE TABLE patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    dob DATE NOT NULL,
    gender VARCHAR(50) NOT NULL,
    contact VARCHAR(255),
    created_by_id BIGINT NOT NULL,
    lab_id BIGINT NOT NULL,
    FOREIGN KEY (lab_id) REFERENCES labs(id),
    FOREIGN KEY (created_by_id) REFERENCES staff_users(id)
);

CREATE TABLE lab_tests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(255),
    price DECIMAL(10, 2) NOT NULL,
    lab_id BIGINT NOT NULL,
    FOREIGN KEY (lab_id) REFERENCES labs(id)
);

CREATE TABLE requisitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    doctor_name VARCHAR(255),
    date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(50),
    created_by_id BIGINT NOT NULL,
    lab_id BIGINT NOT NULL,
    FOREIGN KEY (patient_id) REFERENCES patients(id),
    FOREIGN KEY (created_by_id) REFERENCES staff_users(id),
    FOREIGN KEY (lab_id) REFERENCES labs(id)
);

CREATE TABLE requisition_tests (
    requisition_id BIGINT,
    test_id BIGINT,
    PRIMARY KEY (requisition_id, test_id),
    FOREIGN KEY (requisition_id) REFERENCES requisitions(id),
    FOREIGN KEY (test_id) REFERENCES lab_tests(id)
);

CREATE TABLE inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(255),
    quantity INT DEFAULT 0,
    low_stock_threshold INT DEFAULT 0,
    supplier VARCHAR(255),
    added_by_id BIGINT NOT NULL,
    lab_id BIGINT NOT NULL,
    FOREIGN KEY (added_by_id) REFERENCES staff_users(id),
    FOREIGN KEY (lab_id) REFERENCES labs(id)
);

CREATE TABLE test_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requisition_id BIGINT NOT NULL,
    test_id BIGINT NOT NULL,
    result_value VARCHAR(255) NOT NULL,
    interpretation TEXT,
    entered_by_id BIGINT NOT NULL,
    lab_id BIGINT NOT NULL,
    FOREIGN KEY (requisition_id) REFERENCES requisitions(id),
    FOREIGN KEY (test_id) REFERENCES lab_tests(id),
    FOREIGN KEY (entered_by_id) REFERENCES staff_users(id),
    FOREIGN KEY (lab_id) REFERENCES labs(id),
    UNIQUE (requisition_id, test_id)
);

CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    user_id BIGINT NOT NULL,
    action VARCHAR(255) NOT NULL,
    details TEXT,
    lab_id BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES staff_users(id),
    FOREIGN KEY (lab_id) REFERENCES labs(id)
);
