-- liquibase formatted sql

-- changeset medilab:16-inter-lab-agreements-schema
CREATE TABLE IF NOT EXISTS inter_lab_agreements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    main_lab_id BIGINT NOT NULL,
    partner_lab_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    requested_by_id BIGINT NOT NULL,
    reviewed_by_id BIGINT,
    valid_from TIMESTAMP,
    valid_to TIMESTAMP,
    version INT NOT NULL DEFAULT 1,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (main_lab_id) REFERENCES labs(id),
    FOREIGN KEY (partner_lab_id) REFERENCES labs(id),
    FOREIGN KEY (requested_by_id) REFERENCES staff_users(id),
    FOREIGN KEY (reviewed_by_id) REFERENCES staff_users(id),
    CONSTRAINT chk_different_labs CHECK (main_lab_id != partner_lab_id)
);

CREATE TABLE IF NOT EXISTS agreement_test_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agreement_id BIGINT NOT NULL,
    lab_test_id BIGINT NOT NULL,
    inter_lab_price DECIMAL(10, 2) NOT NULL,
    price_type VARCHAR(50) NOT NULL DEFAULT 'FIXED',
    discount_percentage DECIMAL(5, 2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (agreement_id) REFERENCES inter_lab_agreements(id) ON DELETE CASCADE,
    FOREIGN KEY (lab_test_id) REFERENCES lab_tests(id),
    CONSTRAINT unique_agreement_test UNIQUE (agreement_id, lab_test_id),
    CONSTRAINT chk_price_type CHECK (price_type IN ('FIXED', 'PERCENTAGE_DISCOUNT')),
    CONSTRAINT chk_discount_range CHECK (discount_percentage IS NULL OR (discount_percentage >= 0 AND discount_percentage <= 100))
);

-- Create indexes for better query performance
CREATE INDEX idx_agreements_main_lab ON inter_lab_agreements(main_lab_id);
CREATE INDEX idx_agreements_partner_lab ON inter_lab_agreements(partner_lab_id);
CREATE INDEX idx_agreements_status ON inter_lab_agreements(status);
CREATE INDEX idx_agreement_prices_agreement ON agreement_test_prices(agreement_id);
